import type { ArmorInput, WeaponInput } from './types.js';

/**
 * Basic weapons and armor. The subset is chosen to equip four level-3 pregens
 * and make one adventure work — not to be complete.
 */

export const WEAPONS = {
  // --- Simple melee ---
  club: {
    id: 'club',
    name: 'Club',
    category: 'simple-melee',
    damage: '1d4',
    damageType: 'bludgeoning',
    properties: ['light'],
    weight: 2,
    cost: '1 sp',
  },
  dagger: {
    id: 'dagger',
    name: 'Dagger',
    category: 'simple-melee',
    damage: '1d4',
    damageType: 'piercing',
    properties: ['finesse', 'light', 'thrown'],
    range: [20, 60],
    weight: 1,
    cost: '2 gp',
  },
  handaxe: {
    id: 'handaxe',
    name: 'Handaxe',
    category: 'simple-melee',
    damage: '1d6',
    damageType: 'slashing',
    properties: ['light', 'thrown'],
    range: [20, 60],
    weight: 2,
    cost: '5 gp',
  },
  mace: {
    id: 'mace',
    name: 'Mace',
    category: 'simple-melee',
    damage: '1d6',
    damageType: 'bludgeoning',
    properties: [],
    weight: 4,
    cost: '5 gp',
  },
  quarterstaff: {
    id: 'quarterstaff',
    name: 'Quarterstaff',
    category: 'simple-melee',
    damage: '1d6',
    damageType: 'bludgeoning',
    versatileDamage: '1d8',
    properties: ['versatile'],
    weight: 4,
    cost: '2 sp',
  },
  spear: {
    id: 'spear',
    name: 'Spear',
    category: 'simple-melee',
    damage: '1d6',
    damageType: 'piercing',
    versatileDamage: '1d8',
    properties: ['thrown', 'versatile'],
    range: [20, 60],
    weight: 3,
    cost: '1 gp',
  },

  // --- Simple ranged ---
  'light-crossbow': {
    id: 'light-crossbow',
    name: 'Light Crossbow',
    category: 'simple-ranged',
    damage: '1d8',
    damageType: 'piercing',
    properties: ['ammunition', 'loading', 'two-handed'],
    range: [80, 320],
    weight: 5,
    cost: '25 gp',
  },
  shortbow: {
    id: 'shortbow',
    name: 'Shortbow',
    category: 'simple-ranged',
    damage: '1d6',
    damageType: 'piercing',
    properties: ['ammunition', 'two-handed'],
    range: [80, 320],
    weight: 2,
    cost: '25 gp',
  },

  // --- Martial melee ---
  longsword: {
    id: 'longsword',
    name: 'Longsword',
    category: 'martial-melee',
    damage: '1d8',
    damageType: 'slashing',
    versatileDamage: '1d10',
    properties: ['versatile'],
    weight: 3,
    cost: '15 gp',
  },
  greatsword: {
    id: 'greatsword',
    name: 'Greatsword',
    category: 'martial-melee',
    damage: '2d6',
    damageType: 'slashing',
    properties: ['heavy', 'two-handed'],
    weight: 6,
    cost: '50 gp',
  },
  rapier: {
    id: 'rapier',
    name: 'Rapier',
    category: 'martial-melee',
    damage: '1d8',
    damageType: 'piercing',
    properties: ['finesse'],
    weight: 2,
    cost: '25 gp',
  },
  shortsword: {
    id: 'shortsword',
    name: 'Shortsword',
    category: 'martial-melee',
    damage: '1d6',
    damageType: 'piercing',
    properties: ['finesse', 'light'],
    weight: 2,
    cost: '10 gp',
  },
  battleaxe: {
    id: 'battleaxe',
    name: 'Battleaxe',
    category: 'martial-melee',
    damage: '1d8',
    damageType: 'slashing',
    versatileDamage: '1d10',
    properties: ['versatile'],
    weight: 4,
    cost: '10 gp',
  },
  warhammer: {
    id: 'warhammer',
    name: 'Warhammer',
    category: 'martial-melee',
    damage: '1d8',
    damageType: 'bludgeoning',
    versatileDamage: '1d10',
    properties: ['versatile'],
    weight: 2,
    cost: '15 gp',
  },

  // --- Martial ranged ---
  longbow: {
    id: 'longbow',
    name: 'Longbow',
    category: 'martial-ranged',
    damage: '1d8',
    damageType: 'piercing',
    properties: ['ammunition', 'heavy', 'two-handed'],
    range: [150, 600],
    weight: 2,
    cost: '50 gp',
  },
} as const satisfies Record<string, WeaponInput>;

export type WeaponId = keyof typeof WEAPONS;

export const ARMOR = {
  padded: {
    id: 'padded',
    name: 'Padded',
    category: 'light',
    baseAc: 11,
    maxDexBonus: null,
    stealthDisadvantage: true,
    weight: 8,
    cost: '5 gp',
  },
  leather: {
    id: 'leather',
    name: 'Leather',
    category: 'light',
    baseAc: 11,
    maxDexBonus: null,
    stealthDisadvantage: false,
    weight: 10,
    cost: '10 gp',
  },
  'studded-leather': {
    id: 'studded-leather',
    name: 'Studded Leather',
    category: 'light',
    baseAc: 12,
    maxDexBonus: null,
    stealthDisadvantage: false,
    weight: 13,
    cost: '45 gp',
  },
  hide: {
    id: 'hide',
    name: 'Hide',
    category: 'medium',
    baseAc: 12,
    maxDexBonus: 2,
    stealthDisadvantage: false,
    weight: 12,
    cost: '10 gp',
  },
  'chain-shirt': {
    id: 'chain-shirt',
    name: 'Chain Shirt',
    category: 'medium',
    baseAc: 13,
    maxDexBonus: 2,
    stealthDisadvantage: false,
    weight: 20,
    cost: '50 gp',
  },
  'scale-mail': {
    id: 'scale-mail',
    name: 'Scale Mail',
    category: 'medium',
    baseAc: 14,
    maxDexBonus: 2,
    stealthDisadvantage: true,
    weight: 45,
    cost: '50 gp',
  },
  breastplate: {
    id: 'breastplate',
    name: 'Breastplate',
    category: 'medium',
    baseAc: 14,
    maxDexBonus: 2,
    stealthDisadvantage: false,
    weight: 20,
    cost: '400 gp',
  },
  'ring-mail': {
    id: 'ring-mail',
    name: 'Ring Mail',
    category: 'heavy',
    baseAc: 14,
    maxDexBonus: 0,
    stealthDisadvantage: true,
    weight: 40,
    cost: '30 gp',
  },
  'chain-mail': {
    id: 'chain-mail',
    name: 'Chain Mail',
    category: 'heavy',
    baseAc: 16,
    maxDexBonus: 0,
    strengthRequirement: 13,
    stealthDisadvantage: true,
    weight: 55,
    cost: '75 gp',
  },
  'splint-mail': {
    id: 'splint-mail',
    name: 'Splint',
    category: 'heavy',
    baseAc: 17,
    maxDexBonus: 0,
    strengthRequirement: 15,
    stealthDisadvantage: true,
    weight: 60,
    cost: '200 gp',
  },
  shield: {
    id: 'shield',
    name: 'Shield',
    category: 'shield',
    baseAc: 2,
    maxDexBonus: 0,
    stealthDisadvantage: false,
    weight: 6,
    cost: '10 gp',
  },
} as const satisfies Record<string, ArmorInput>;

export type ArmorId = keyof typeof ARMOR;
