import type { MonsterInput } from './types.js';

/**
 * ~15 monsters. Chosen to populate one level-3 adventure: fodder, a mid-tier
 * threat band, undead for the crypt beats, and two boss-capable creatures.
 * CR spread runs 1/8 to 3 so the linter's solvability check has real cases.
 */
export const MONSTERS = {
  // ---------------------------------------------------------------- CR 1/8–1/4
  bandit: {
    id: 'bandit',
    name: 'Bandit',
    size: 'medium',
    type: 'humanoid',
    ac: 12,
    hp: 11,
    hitDice: '2d8+2',
    speed: 30,
    abilities: { str: 11, dex: 12, con: 12, int: 10, wis: 10, cha: 10 },
    cr: 0.125,
    xp: 25,
    attacks: [
      { name: 'Scimitar', toHit: 3, reach: 5, damage: '1d6+1', damageType: 'slashing' },
      { name: 'Light Crossbow', toHit: 3, range: [80, 320], damage: '1d8+1', damageType: 'piercing' },
    ],
    multiattack: 1,
    senses: [],
    traits: [],
  },
  'giant-rat': {
    id: 'giant-rat',
    name: 'Giant Rat',
    size: 'small',
    type: 'beast',
    ac: 12,
    hp: 7,
    hitDice: '2d6',
    speed: 30,
    abilities: { str: 7, dex: 15, con: 11, int: 2, wis: 10, cha: 4 },
    cr: 0.125,
    xp: 25,
    attacks: [{ name: 'Bite', toHit: 4, reach: 5, damage: '1d4+2', damageType: 'piercing' }],
    multiattack: 1,
    senses: ['darkvision 60 ft.'],
    traits: [
      { name: 'Keen Smell', text: 'Advantage on Wisdom (Perception) checks that rely on smell.' },
      { name: 'Pack Tactics', text: 'Advantage on attack rolls when an ally is within 5 feet of the target.' },
    ],
  },
  kobold: {
    id: 'kobold',
    name: 'Kobold',
    size: 'small',
    type: 'humanoid',
    ac: 12,
    hp: 5,
    hitDice: '2d6-2',
    speed: 30,
    abilities: { str: 7, dex: 15, con: 9, int: 8, wis: 7, cha: 8 },
    cr: 0.125,
    xp: 25,
    attacks: [
      { name: 'Dagger', toHit: 4, reach: 5, damage: '1d4+2', damageType: 'piercing' },
      { name: 'Sling', toHit: 4, range: [30, 120], damage: '1d4+2', damageType: 'bludgeoning' },
    ],
    multiattack: 1,
    senses: ['darkvision 60 ft.'],
    traits: [
      { name: 'Sunlight Sensitivity', text: 'Disadvantage on attack rolls and Perception checks in sunlight.' },
      { name: 'Pack Tactics', text: 'Advantage on attack rolls when an ally is within 5 feet of the target.' },
    ],
  },
  skeleton: {
    id: 'skeleton',
    name: 'Skeleton',
    size: 'medium',
    type: 'undead',
    ac: 13,
    hp: 13,
    hitDice: '2d8+4',
    speed: 30,
    abilities: { str: 10, dex: 14, con: 15, int: 6, wis: 8, cha: 5 },
    cr: 0.25,
    xp: 50,
    attacks: [
      { name: 'Shortsword', toHit: 4, reach: 5, damage: '1d6+2', damageType: 'piercing' },
      { name: 'Shortbow', toHit: 4, range: [80, 320], damage: '1d6+2', damageType: 'piercing' },
    ],
    multiattack: 1,
    damageImmunities: ['poison'],
    conditionImmunities: ['poisoned'],
    senses: ['darkvision 60 ft.'],
    traits: [{ name: 'Vulnerability', text: 'Vulnerable to bludgeoning damage.' }],
  },
  zombie: {
    id: 'zombie',
    name: 'Zombie',
    size: 'medium',
    type: 'undead',
    ac: 8,
    hp: 22,
    hitDice: '3d8+9',
    speed: 20,
    abilities: { str: 13, dex: 6, con: 16, int: 3, wis: 6, cha: 5 },
    cr: 0.25,
    xp: 50,
    attacks: [{ name: 'Slam', toHit: 3, reach: 5, damage: '1d6+1', damageType: 'bludgeoning' }],
    multiattack: 1,
    damageImmunities: ['poison'],
    conditionImmunities: ['poisoned'],
    senses: ['darkvision 60 ft.'],
    traits: [
      {
        name: 'Undead Fortitude',
        text: 'On dropping to 0 HP from non-radiant, non-critical damage, makes a CON save (DC 5 + damage taken); on success drops to 1 HP instead.',
      },
    ],
  },
  goblin: {
    id: 'goblin',
    name: 'Goblin',
    size: 'small',
    type: 'humanoid',
    ac: 15,
    hp: 7,
    hitDice: '2d6',
    speed: 30,
    abilities: { str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8 },
    cr: 0.25,
    xp: 50,
    attacks: [
      { name: 'Scimitar', toHit: 4, reach: 5, damage: '1d6+2', damageType: 'slashing' },
      { name: 'Shortbow', toHit: 4, range: [80, 320], damage: '1d6+2', damageType: 'piercing' },
    ],
    multiattack: 1,
    skills: ['stealth'],
    senses: ['darkvision 60 ft.'],
    traits: [
      { name: 'Nimble Escape', text: 'Can Disengage or Hide as a bonus action on each of its turns.' },
    ],
  },
  wolf: {
    id: 'wolf',
    name: 'Wolf',
    size: 'medium',
    type: 'beast',
    ac: 13,
    hp: 11,
    hitDice: '2d8+2',
    speed: 40,
    abilities: { str: 12, dex: 15, con: 12, int: 3, wis: 12, cha: 6 },
    cr: 0.25,
    xp: 50,
    attacks: [
      {
        name: 'Bite',
        toHit: 4,
        reach: 5,
        damage: '2d4+2',
        damageType: 'piercing',
        save: { ability: 'str', dc: 11, onFail: 'prone' },
      },
    ],
    multiattack: 1,
    skills: ['perception', 'stealth'],
    senses: [],
    traits: [
      { name: 'Pack Tactics', text: 'Advantage on attack rolls when an ally is within 5 feet of the target.' },
    ],
  },

  // ------------------------------------------------------------------ CR 1/2–1
  'hobgoblin': {
    id: 'hobgoblin',
    name: 'Hobgoblin',
    size: 'medium',
    type: 'humanoid',
    ac: 18,
    hp: 11,
    hitDice: '2d8+2',
    speed: 30,
    abilities: { str: 13, dex: 12, con: 12, int: 10, wis: 10, cha: 9 },
    cr: 0.5,
    xp: 100,
    attacks: [
      { name: 'Longsword', toHit: 3, reach: 5, damage: '1d8+1', damageType: 'slashing' },
      { name: 'Longbow', toHit: 3, range: [150, 600], damage: '1d8+1', damageType: 'piercing' },
    ],
    multiattack: 1,
    senses: ['darkvision 60 ft.'],
    traits: [
      {
        name: 'Martial Advantage',
        text: 'Once per turn, deals an extra 2d6 damage to a creature within 5 feet of an ally.',
      },
    ],
  },
  'shadow': {
    id: 'shadow',
    name: 'Shadow',
    size: 'medium',
    type: 'undead',
    ac: 12,
    hp: 16,
    hitDice: '3d8+3',
    speed: 40,
    abilities: { str: 6, dex: 14, con: 13, int: 6, wis: 10, cha: 8 },
    cr: 0.5,
    xp: 100,
    attacks: [
      { name: 'Strength Drain', toHit: 4, reach: 5, damage: '2d6+2', damageType: 'necrotic' },
    ],
    multiattack: 1,
    damageResistances: ['acid', 'cold', 'fire', 'lightning', 'thunder'],
    damageImmunities: ['necrotic', 'poison'],
    conditionImmunities: ['frightened', 'grappled', 'paralyzed', 'petrified', 'poisoned', 'prone', 'restrained'],
    skills: ['stealth'],
    senses: ['darkvision 60 ft.'],
    traits: [
      { name: 'Amorphous', text: 'Can move through a space as narrow as 1 inch wide.' },
      { name: 'Shadow Stealth', text: 'While in dim light or darkness, can Hide as a bonus action.' },
      { name: 'Sunlight Weakness', text: 'Disadvantage on attacks, checks, and saves in sunlight.' },
    ],
  },
  ghoul: {
    id: 'ghoul',
    name: 'Ghoul',
    size: 'medium',
    type: 'undead',
    ac: 12,
    hp: 22,
    hitDice: '5d8',
    speed: 30,
    abilities: { str: 13, dex: 15, con: 10, int: 7, wis: 10, cha: 6 },
    cr: 1,
    xp: 200,
    attacks: [
      { name: 'Bite', toHit: 2, reach: 5, damage: '2d6+2', damageType: 'piercing' },
      {
        name: 'Claws',
        toHit: 4,
        reach: 5,
        damage: '2d4+2',
        damageType: 'slashing',
        save: { ability: 'con', dc: 10, onFail: 'paralyzed' },
      },
    ],
    multiattack: 1,
    damageImmunities: ['poison'],
    conditionImmunities: ['charmed', 'poisoned'],
    senses: ['darkvision 60 ft.'],
    traits: [],
  },
  'dire-wolf': {
    id: 'dire-wolf',
    name: 'Dire Wolf',
    size: 'large',
    type: 'beast',
    ac: 14,
    hp: 37,
    hitDice: '5d10+10',
    speed: 50,
    abilities: { str: 17, dex: 15, con: 15, int: 3, wis: 12, cha: 7 },
    cr: 1,
    xp: 200,
    attacks: [
      {
        name: 'Bite',
        toHit: 5,
        reach: 5,
        damage: '2d6+3',
        damageType: 'piercing',
        save: { ability: 'str', dc: 13, onFail: 'prone' },
      },
    ],
    multiattack: 1,
    skills: ['perception', 'stealth'],
    senses: [],
    traits: [
      { name: 'Pack Tactics', text: 'Advantage on attack rolls when an ally is within 5 feet of the target.' },
    ],
  },
  'animated-armor': {
    id: 'animated-armor',
    name: 'Animated Armor',
    size: 'medium',
    type: 'construct',
    ac: 18,
    hp: 33,
    hitDice: '6d8+6',
    speed: 25,
    abilities: { str: 14, dex: 11, con: 13, int: 1, wis: 3, cha: 1 },
    cr: 1,
    xp: 200,
    attacks: [{ name: 'Slam', toHit: 4, reach: 5, damage: '1d6+2', damageType: 'bludgeoning' }],
    multiattack: 2,
    damageImmunities: ['poison', 'psychic'],
    conditionImmunities: ['blinded', 'charmed', 'deafened', 'frightened', 'paralyzed', 'petrified', 'poisoned'],
    senses: ['blindsight 60 ft.'],
    traits: [
      { name: 'False Appearance', text: 'Indistinguishable from a normal suit of armor while motionless.' },
    ],
  },

  // -------------------------------------------------------------------- CR 2–3
  'ogre': {
    id: 'ogre',
    name: 'Ogre',
    size: 'large',
    type: 'giant',
    ac: 11,
    hp: 59,
    hitDice: '7d10+21',
    speed: 40,
    abilities: { str: 19, dex: 8, con: 16, int: 5, wis: 7, cha: 7 },
    cr: 2,
    xp: 450,
    attacks: [
      { name: 'Greatclub', toHit: 6, reach: 5, damage: '2d8+4', damageType: 'bludgeoning' },
      { name: 'Javelin', toHit: 6, range: [30, 120], damage: '2d6+4', damageType: 'piercing' },
    ],
    multiattack: 1,
    senses: ['darkvision 60 ft.'],
    traits: [],
  },
  'ghast': {
    id: 'ghast',
    name: 'Ghast',
    size: 'medium',
    type: 'undead',
    ac: 13,
    hp: 36,
    hitDice: '8d8',
    speed: 30,
    abilities: { str: 16, dex: 17, con: 10, int: 11, wis: 10, cha: 8 },
    cr: 2,
    xp: 450,
    attacks: [
      { name: 'Bite', toHit: 3, reach: 5, damage: '2d8+3', damageType: 'piercing' },
      {
        name: 'Claws',
        toHit: 5,
        reach: 5,
        damage: '2d6+3',
        damageType: 'slashing',
        save: { ability: 'con', dc: 10, onFail: 'paralyzed' },
      },
    ],
    multiattack: 1,
    damageResistances: ['necrotic'],
    damageImmunities: ['poison'],
    conditionImmunities: ['charmed', 'poisoned'],
    senses: ['darkvision 60 ft.'],
    traits: [
      {
        name: 'Stench',
        text: 'A creature starting its turn within 5 feet must succeed on a DC 10 CON save or be poisoned until the start of its next turn.',
      },
    ],
  },
  'bandit-captain': {
    id: 'bandit-captain',
    name: 'Bandit Captain',
    size: 'medium',
    type: 'humanoid',
    ac: 15,
    hp: 65,
    hitDice: '10d8+20',
    speed: 30,
    abilities: { str: 15, dex: 16, con: 14, int: 14, wis: 11, cha: 14 },
    cr: 2,
    xp: 450,
    attacks: [
      { name: 'Scimitar', toHit: 5, reach: 5, damage: '1d6+3', damageType: 'slashing' },
      { name: 'Dagger', toHit: 5, range: [20, 60], damage: '1d4+3', damageType: 'piercing' },
    ],
    multiattack: 3,
    skills: ['athletics', 'deception'],
    senses: [],
    traits: [
      {
        name: 'Parry',
        text: 'Reaction: adds 2 to its AC against one melee attack that would hit it.',
      },
    ],
  },
  'wight': {
    id: 'wight',
    name: 'Wight',
    size: 'medium',
    type: 'undead',
    ac: 14,
    hp: 45,
    hitDice: '6d8+18',
    speed: 30,
    abilities: { str: 15, dex: 14, con: 16, int: 10, wis: 13, cha: 15 },
    cr: 3,
    xp: 700,
    attacks: [
      { name: 'Life Drain', toHit: 4, reach: 5, damage: '1d6+2', damageType: 'necrotic' },
      { name: 'Longsword', toHit: 4, reach: 5, damage: '1d8+2', damageType: 'slashing' },
      { name: 'Longbow', toHit: 4, range: [150, 600], damage: '1d8+2', damageType: 'piercing' },
    ],
    multiattack: 2,
    damageResistances: ['necrotic'],
    damageImmunities: ['poison'],
    conditionImmunities: ['poisoned'],
    skills: ['perception', 'stealth'],
    senses: ['darkvision 60 ft.'],
    traits: [
      {
        name: 'Sunlight Sensitivity',
        text: 'Disadvantage on attack rolls and Perception checks in sunlight.',
      },
      {
        name: 'Life Drain',
        text: 'A creature hit must succeed on a DC 13 CON save or its HP maximum is reduced by the damage taken until it finishes a long rest.',
      },
    ],
  },
} as const satisfies Record<string, MonsterInput>;

export type MonsterId = keyof typeof MONSTERS;
