import type { SpellInput } from './types.js';

/**
 * ~30 spells, chosen to make one adventure work rather than to be complete.
 * The full list is on the cut list.
 *
 * Coverage target: enough for a level-3 Cleric and a level-3 Wizard to play a
 * full session — attack cantrips, healing, a save-or-suck, an area effect, and
 * a handful of utility spells that create non-combat options.
 */
export const LEGACY_SPELLS = {
  // ------------------------------------------------------------------ cantrips
  'fire-bolt': {
    id: 'fire-bolt',
    name: 'Fire Bolt',
    level: 0,
    school: 'evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: ['V', 'S'],
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    resolution: { kind: 'attack', ranged: true },
    damage: '1d10',
    damageType: 'fire',
    classes: ['sorcerer', 'wizard'],
    text: 'A mote of fire streaks toward a creature or object within range.',
  },
  'ray-of-frost': {
    id: 'ray-of-frost',
    name: 'Ray of Frost',
    level: 0,
    school: 'evocation',
    castingTime: '1 action',
    range: '60 feet',
    components: ['V', 'S'],
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    resolution: { kind: 'attack', ranged: true },
    damage: '1d8',
    damageType: 'cold',
    classes: ['sorcerer', 'wizard'],
    text: 'A frigid beam of blue-white light streaks toward a creature. Its speed is reduced by 10 feet until the start of your next turn.',
  },
  'sacred-flame': {
    id: 'sacred-flame',
    name: 'Sacred Flame',
    level: 0,
    school: 'evocation',
    castingTime: '1 action',
    range: '60 feet',
    components: ['V', 'S'],
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    resolution: { kind: 'save', ability: 'dex', halfOnSave: false },
    damage: '1d8',
    damageType: 'radiant',
    classes: ['cleric'],
    text: 'Flame-like radiance descends on a creature. It gains no benefit from cover for this saving throw.',
  },
  guidance: {
    id: 'guidance',
    name: 'Guidance',
    level: 0,
    school: 'divination',
    castingTime: '1 action',
    range: 'Touch',
    components: ['V', 'S'],
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    resolution: { kind: 'none' },
    classes: ['cleric', 'druid'],
    text: 'The target can roll a d4 and add the number to one ability check of its choice.',
  },
  light: {
    id: 'light',
    name: 'Light',
    level: 0,
    school: 'evocation',
    castingTime: '1 action',
    range: 'Touch',
    components: ['V', 'M'],
    materials: 'a firefly or phosphorescent moss',
    duration: '1 hour',
    concentration: false,
    ritual: false,
    resolution: { kind: 'none' },
    classes: ['bard', 'cleric', 'sorcerer', 'wizard'],
    text: 'An object sheds bright light in a 20-foot radius and dim light for an additional 20 feet.',
  },
  'mage-hand': {
    id: 'mage-hand',
    name: 'Mage Hand',
    level: 0,
    school: 'conjuration',
    castingTime: '1 action',
    range: '30 feet',
    components: ['V', 'S'],
    duration: '1 minute',
    concentration: false,
    ritual: false,
    resolution: { kind: 'none' },
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    text: 'A spectral hand appears and can manipulate objects, open doors, and retrieve items up to 10 pounds.',
  },
  prestidigitation: {
    id: 'prestidigitation',
    name: 'Prestidigitation',
    level: 0,
    school: 'transmutation',
    castingTime: '1 action',
    range: '10 feet',
    components: ['V', 'S'],
    duration: 'Up to 1 hour',
    concentration: false,
    ritual: false,
    resolution: { kind: 'none' },
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    text: 'A minor magical trick: a sensory effect, lighting or snuffing a flame, cleaning or soiling an object.',
  },
  thaumaturgy: {
    id: 'thaumaturgy',
    name: 'Thaumaturgy',
    level: 0,
    school: 'transmutation',
    castingTime: '1 action',
    range: '30 feet',
    components: ['V'],
    duration: 'Up to 1 minute',
    concentration: false,
    ritual: false,
    resolution: { kind: 'none' },
    classes: ['cleric'],
    text: 'A minor wonder: a booming voice, flickering flames, tremors, or doors flying open.',
  },

  // ------------------------------------------------------------------- level 1
  'magic-missile': {
    id: 'magic-missile',
    name: 'Magic Missile',
    level: 1,
    school: 'evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: ['V', 'S'],
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    resolution: { kind: 'none' },
    damage: '3d4+3',
    damageType: 'force',
    upcastDamage: '1d4',
    classes: ['sorcerer', 'wizard'],
    text: 'Three glowing darts each strike a creature for 1d4+1 force damage. They automatically hit.',
  },
  shield: {
    id: 'shield',
    name: 'Shield',
    level: 1,
    school: 'abjuration',
    castingTime: '1 reaction',
    range: 'Self',
    components: ['V', 'S'],
    duration: '1 round',
    concentration: false,
    ritual: false,
    resolution: { kind: 'none' },
    classes: ['sorcerer', 'wizard'],
    text: 'An invisible barrier grants +5 AC until the start of your next turn, including against the triggering attack.',
  },
  sleep: {
    id: 'sleep',
    name: 'Sleep',
    level: 1,
    school: 'enchantment',
    castingTime: '1 action',
    range: '90 feet',
    components: ['V', 'S', 'M'],
    materials: 'a pinch of fine sand, rose petals, or a cricket',
    duration: '1 minute',
    concentration: false,
    ritual: false,
    resolution: { kind: 'none' },
    damage: '5d8',
    appliesCondition: 'unconscious',
    upcastDamage: '2d8',
    classes: ['bard', 'sorcerer', 'wizard'],
    text: 'Roll 5d8; that total is how many hit points of creatures this spell affects, lowest current HP first.',
  },
  'burning-hands': {
    id: 'burning-hands',
    name: 'Burning Hands',
    level: 1,
    school: 'evocation',
    castingTime: '1 action',
    range: 'Self (15-foot cone)',
    components: ['V', 'S'],
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    resolution: { kind: 'save', ability: 'dex', halfOnSave: true },
    damage: '3d6',
    damageType: 'fire',
    upcastDamage: '1d6',
    classes: ['sorcerer', 'wizard'],
    text: 'A thin sheet of flames shoots from your fingertips in a 15-foot cone.',
  },
  'cure-wounds': {
    id: 'cure-wounds',
    name: 'Cure Wounds',
    level: 1,
    school: 'evocation',
    castingTime: '1 action',
    range: 'Touch',
    components: ['V', 'S'],
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    resolution: { kind: 'none' },
    healing: '1d8',
    classes: ['bard', 'cleric', 'druid', 'paladin', 'ranger'],
    text: 'A creature you touch regains hit points equal to 1d8 + your spellcasting ability modifier.',
  },
  bless: {
    id: 'bless',
    name: 'Bless',
    level: 1,
    school: 'enchantment',
    castingTime: '1 action',
    range: '30 feet',
    components: ['V', 'S', 'M'],
    materials: 'a sprinkling of holy water',
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    resolution: { kind: 'none' },
    classes: ['cleric', 'paladin'],
    text: 'Up to three creatures add 1d4 to attack rolls and saving throws.',
  },
  'shield-of-faith': {
    id: 'shield-of-faith',
    name: 'Shield of Faith',
    level: 1,
    school: 'abjuration',
    castingTime: '1 bonus action',
    range: '60 feet',
    components: ['V', 'S', 'M'],
    materials: 'a small parchment with holy text',
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: false,
    resolution: { kind: 'none' },
    classes: ['cleric', 'paladin'],
    text: 'A shimmering field grants a creature +2 AC.',
  },
  command: {
    id: 'command',
    name: 'Command',
    level: 1,
    school: 'enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: ['V'],
    duration: '1 round',
    concentration: false,
    ritual: false,
    resolution: { kind: 'save', ability: 'wis', halfOnSave: false },
    classes: ['cleric', 'paladin'],
    text: 'You speak a one-word command. The target obeys on its next turn if it fails a Wisdom save.',
  },
  'detect-magic': {
    id: 'detect-magic',
    name: 'Detect Magic',
    level: 1,
    school: 'divination',
    castingTime: '1 action',
    range: 'Self (30-foot radius)',
    components: ['V', 'S'],
    duration: 'Concentration, up to 10 minutes',
    concentration: true,
    ritual: true,
    resolution: { kind: 'none' },
    classes: ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'sorcerer', 'wizard'],
    text: 'You sense the presence of magic within 30 feet and can identify its school.',
  },
  'healing-word': {
    id: 'healing-word',
    name: 'Healing Word',
    level: 1,
    school: 'evocation',
    castingTime: '1 bonus action',
    range: '60 feet',
    components: ['V'],
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    resolution: { kind: 'none' },
    healing: '1d4',
    classes: ['bard', 'cleric', 'druid'],
    text: 'A creature you can see regains 1d4 + your spellcasting ability modifier hit points.',
  },
  'guiding-bolt': {
    id: 'guiding-bolt',
    name: 'Guiding Bolt',
    level: 1,
    school: 'evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: ['V', 'S'],
    duration: '1 round',
    concentration: false,
    ritual: false,
    resolution: { kind: 'attack', ranged: true },
    damage: '4d6',
    damageType: 'radiant',
    upcastDamage: '1d6',
    classes: ['cleric'],
    text: 'A flash of light strikes a creature. The next attack roll against it has advantage.',
  },
  'feather-fall': {
    id: 'feather-fall',
    name: 'Feather Fall',
    level: 1,
    school: 'transmutation',
    castingTime: '1 reaction',
    range: '60 feet',
    components: ['V', 'M'],
    materials: 'a small feather or piece of down',
    duration: '1 minute',
    concentration: false,
    ritual: false,
    resolution: { kind: 'none' },
    classes: ['bard', 'sorcerer', 'wizard'],
    text: 'Up to five falling creatures descend 60 feet per round and take no falling damage.',
  },

  // ------------------------------------------------------------------- level 2
  'hold-person': {
    id: 'hold-person',
    name: 'Hold Person',
    level: 2,
    school: 'enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: ['V', 'S', 'M'],
    materials: 'a small straight piece of iron',
    duration: 'Concentration, up to 1 minute',
    concentration: true,
    ritual: false,
    resolution: { kind: 'save', ability: 'wis', halfOnSave: false },
    appliesCondition: 'paralyzed',
    classes: ['bard', 'cleric', 'druid', 'sorcerer', 'warlock', 'wizard'],
    text: 'A humanoid must succeed on a Wisdom save or be paralyzed. It repeats the save at the end of each turn.',
  },
  'misty-step': {
    id: 'misty-step',
    name: 'Misty Step',
    level: 2,
    school: 'conjuration',
    castingTime: '1 bonus action',
    range: 'Self',
    components: ['V'],
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    resolution: { kind: 'none' },
    classes: ['sorcerer', 'warlock', 'wizard'],
    text: 'You teleport up to 30 feet to an unoccupied space you can see.',
  },
  invisibility: {
    id: 'invisibility',
    name: 'Invisibility',
    level: 2,
    school: 'illusion',
    castingTime: '1 action',
    range: 'Touch',
    components: ['V', 'S', 'M'],
    materials: 'an eyelash encased in gum arabic',
    duration: 'Concentration, up to 1 hour',
    concentration: true,
    ritual: false,
    resolution: { kind: 'none' },
    appliesCondition: 'invisible',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
    text: 'A creature becomes invisible until it attacks or casts a spell.',
  },
  'scorching-ray': {
    id: 'scorching-ray',
    name: 'Scorching Ray',
    level: 2,
    school: 'evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: ['V', 'S'],
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    resolution: { kind: 'attack', ranged: true },
    damage: '2d6',
    damageType: 'fire',
    classes: ['sorcerer', 'wizard'],
    text: 'Three rays of fire, each a separate attack roll for 2d6 fire damage.',
  },
  'spiritual-weapon': {
    id: 'spiritual-weapon',
    name: 'Spiritual Weapon',
    level: 2,
    school: 'evocation',
    castingTime: '1 bonus action',
    range: '60 feet',
    components: ['V', 'S'],
    duration: '1 minute',
    concentration: false,
    ritual: false,
    resolution: { kind: 'attack', ranged: false },
    damage: '1d8',
    damageType: 'force',
    classes: ['cleric'],
    text: 'A spectral weapon appears and attacks as a bonus action on subsequent turns.',
  },
  'lesser-restoration': {
    id: 'lesser-restoration',
    name: 'Lesser Restoration',
    level: 2,
    school: 'abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: ['V', 'S'],
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    resolution: { kind: 'none' },
    classes: ['bard', 'cleric', 'druid', 'paladin', 'ranger'],
    text: 'You end one disease or the blinded, deafened, paralyzed, or poisoned condition.',
  },
  'mirror-image': {
    id: 'mirror-image',
    name: 'Mirror Image',
    level: 2,
    school: 'illusion',
    castingTime: '1 action',
    range: 'Self',
    components: ['V', 'S'],
    duration: '1 minute',
    concentration: false,
    ritual: false,
    resolution: { kind: 'none' },
    classes: ['sorcerer', 'warlock', 'wizard'],
    text: 'Three illusory duplicates appear. Attacks may strike a duplicate instead of you.',
  },
  'hold-portal': {
    id: 'hold-portal',
    name: 'Hold Portal',
    level: 2,
    school: 'abjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: ['V', 'S'],
    duration: '1 minute',
    concentration: false,
    ritual: false,
    resolution: { kind: 'none' },
    classes: ['wizard'],
    text: 'A door, gate, or window is magically held shut.',
  },

  // ------------------------------------------------------------------- level 3
  fireball: {
    id: 'fireball',
    name: 'Fireball',
    level: 3,
    school: 'evocation',
    castingTime: '1 action',
    range: '150 feet',
    components: ['V', 'S', 'M'],
    materials: 'a tiny ball of bat guano and sulfur',
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    resolution: { kind: 'save', ability: 'dex', halfOnSave: true },
    damage: '8d6',
    damageType: 'fire',
    upcastDamage: '1d6',
    classes: ['sorcerer', 'wizard'],
    text: 'A bright streak blossoms into an explosion of flame in a 20-foot radius.',
  },
  counterspell: {
    id: 'counterspell',
    name: 'Counterspell',
    level: 3,
    school: 'abjuration',
    castingTime: '1 reaction',
    range: '60 feet',
    components: ['S'],
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    resolution: { kind: 'none' },
    classes: ['sorcerer', 'warlock', 'wizard'],
    text: 'You attempt to interrupt a creature in the process of casting a spell.',
  },
  'dispel-magic': {
    id: 'dispel-magic',
    name: 'Dispel Magic',
    level: 3,
    school: 'abjuration',
    castingTime: '1 action',
    range: '120 feet',
    components: ['V', 'S'],
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    resolution: { kind: 'none' },
    classes: ['bard', 'cleric', 'druid', 'paladin', 'sorcerer', 'warlock', 'wizard'],
    text: 'Any spell of 3rd level or lower on the target ends.',
  },
  'revivify': {
    id: 'revivify',
    name: 'Revivify',
    level: 3,
    school: 'necromancy',
    castingTime: '1 action',
    range: 'Touch',
    components: ['V', 'S', 'M'],
    materials: 'diamonds worth 300 gp, which the spell consumes',
    duration: 'Instantaneous',
    concentration: false,
    ritual: false,
    resolution: { kind: 'none' },
    classes: ['cleric', 'paladin'],
    text: 'A creature that died within the last minute returns to life with 1 hit point.',
  },
} as const satisfies Record<string, SpellInput>;

export type LegacySpellId = keyof typeof LEGACY_SPELLS;
